<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE siop_document [
<!ELEMENT siop_document (temperatures, levels, components, scenarios?)>
<!ELEMENT temperatures (temp+)>
<!ELEMENT temp EMPTY>
<!ATTLIST temp
          type (AP|BAT|USB|CHG|PA|WIFI) #REQUIRED
          default CDATA "1"
          min CDATA "1"
          max CDATA "1"
          step CDATA "1"
          init CDATA "5"
          hold CDATA "1"
          gap CDATA "0">
<!ELEMENT levels (level+)>
<!ELEMENT level EMPTY>
<!ATTLIST level
          id CDATA #REQUIRED
          temp CDATA #REQUIRED>
<!ELEMENT components (default, complex?)>
<!ELEMENT default (component+)>
<!ELEMENT complex (component+)>
<!ELEMENT component (limiter+)>
<!ATTLIST component
          name CDATA #REQUIRED
          tempType CDATA #REQUIRED>
<!ELEMENT scenarios (scenario*, scenario_group*)>
<!ELEMENT scenario (limiter+)>
<!-- you can use below delimiter on scenario name -->
<!-- "!" : intent, ":" : package, "," : plural    -->
<!ATTLIST scenario
          name CDATA #REQUIRED
          tempType CDATA #REQUIRED
          priority CDATA "0">
<!ELEMENT scenario_group (scenario+)>
<!ELEMENT scenario EMPTY>
<!ATTLIST scenario
          name CDATA #REQUIRED
          limiter CDATA #REQUIRED
          step CDATA "-1"
          delay CDATA "0"
          cond (sensor_check|for_request|for_temporary) #IMPLIED
          temp CDATA "370"
          gap CDATA "20"
          value CDATA #REQUIRED>
<!ELEMENT limiter EMPTY>
<!ATTLIST limiter
          name CDATA #REQUIRED
          step CDATA "-1"
          delay CDATA "0"
          cond (sensor_check|for_request|for_temporary) #IMPLIED
          temp CDATA "370"
          gap CDATA "20"
          value CDATA #REQUIRED>
]>

<siop_document>

    <overheatcontrol>
        <complex>
            <LTB    formula="AP*BAT*PA"  temp="530.465.510" />
            <LCD    formula="AP*BAT*PA"  temp="510.450.490" />
            <GDM    formula="AP*LRP*PA"  temp="485.430.470" />
            <GDMLTB formula="AP*LRP*PA"  temp="510.450.490" />
            <SS     formula="AP*BAT*PA"  temp="700.475.800" />
            <SS     formula="AP*BAT*PA"  temp="710.510.670" region="China" />
            <SS     formula="AP*LRP*PA"  temp="590.520.592" region="JP" />
        </complex>
    </overheatcontrol>

    <modelsettings>
        <Skin type="LRP2"/>
        <sensors>
            <LTB_SENSOR type="PALM" />
        </sensors>
    </modelsettings>

    <components>

        <component name="AP" tempType="SKIN" >
            <limiter name="CPUFreqMax" step="0" temp="360:380:450:470" value="-1:1536000:1536000:1056000" />
            <limiter name="OverLimit"           temp="380:400:420"     value="2208000:1632000:-1" />
            <limiter name="CPUFreqLittleMax"    temp="450"             value="-1:1056000" />
            <limiter name="GPUFreqMax" step="0" temp="360:380:450:470" value="-1:611000:611000:403000" />
        </component>

        <component name="DISPLAY" tempType="SKIN">
            <limiter name="Brightness"  temp="409:410:430:450:470"         value="-1:204:149:144:115" />
            <limiter name="MultiWindow" temp="450:470:500"                 value="-1:1:1" delay="0:300:0" />
        </component>

        <component name="CP" tempType="LRP*LRP2">
            <limiter name="CpLowMode" temp="340.340:360.360:410.410:430.430" value="-1:2:2:1" />
            <limiter name="CpLowMode" temp="410.410:430.430" value="-1:1" region="China" />
            <limiter name="NrCCDrop"  temp="410.410:420.420" value="-1:1" />
            <limiter name="SADisable" temp="410.410:440.440" value="-1:1" />
            <limiter name="LteCCDrop" temp="430.430:450.450" value="-1:1" />
        </component>

        <component name="CP" tempType="SKIN" region="XSG" >
            <limiter name="CpLowMode" temp="410:430" value="-1:1" />
            <limiter name="SADisable" temp="410:440" value="-1:1" />
        </component>

        <component name="CP" tempType="SKIN" region="KSA" >
            <limiter name="CpLowMode" temp="410:430" value="-1:1" />
            <limiter name="SADisable" temp="410:440" value="-1:1" />
        </component>
        
        <component name="CHG+DISPLAY" tempType="SKIN">
            <limiter name="Charging" temp="360" value="-1:70" />
        </component>

    </components>

    <scenarios>

        <scenario name="ScreenOffInCall" tempType="SKIN" priority="1" >
            <limiter name="Charging" value="70" />
        </scenario>

        <scenario name="SIPStart" tempType="SKIN" priority="3" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450:470" value="-1:1632000" />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450:470" value="-1:611000"  />
        </scenario>

        <scenario name="AppStart" tempType="SKIN" priority="3" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450:470" value="-1:1632000" />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450:470" value="-1:611000"  />
        </scenario>

        <scenario name="Badge" tempType="SKIN" priority="3" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450:470" value="-1:1632000" />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450:470" value="-1:611000"  />
        </scenario>

        <scenario name="CallStart" tempType="SKIN" priority="3" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450:470" value="-1:1632000" />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450:470" value="-1:611000"  />
        </scenario>

        <scenario name="WakeUp" tempType="SKIN" priority="3" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450:470" value="-1:1632000" />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450:470" value="-1:611000"  />
        </scenario>

        <scenario name="VtCallControl" tempType="SKIN" priority="3">
            <limiter name="CPUFreqMax" step="0" temp="340:360:410:430:450:470" value="1632000:1344000:1344000:1152000:1152000:1056000" />
            <limiter name="CPUFreqLittleMax" temp="340:380:400:430:450"        value="1728000:1728000:1536000:1536000:1344000" />
            <limiter name="Brightness" temp="320:340:410:430:450:470" value="-1:204:204:149:144:115" />
            <limiter name="CameraFps"  temp="340" value="-1:1" />
            <limiter name="Charging"   temp="320"     value="-1:70" />
        </scenario>

        <scenario name="SecVtCall" tempType="SKIN" priority="3" region="China">
            <limiter name="CameraFps"  temp="360" value="-1:1" />
        </scenario>

        <scenario name="LiveCam" tempType="SKIN" priority="3">
            <limiter name="CPUFreqMax" step="0" temp="340:360:410:430:450:470" value="1632000:1344000:1344000:1152000:1152000:1056000" />
            <limiter name="CPUFreqLittleMax" temp="340:380:400:430:450"        value="1728000:1728000:1536000:1536000:1344000" />
            <limiter name="Brightness" temp="320:340:410:430:450:470" value="-1:204:204:149:144:115" />
            <limiter name="Charging"   temp="320"     value="-1:70" />
        </scenario>

        <scenario name="CameraRecording!Camera_recording,Camera_recordingDual" tempType="SKIN" priority="1" >
            <limiter name="Brightness" temp="330:350:390:410:430:450" value="-1:255:255:204:149:121" />
        </scenario>

        <scenario name="Navigation" tempType="SKIN" priority="1" >
            <limiter name="Brightness" temp="410" value="174:149:144:115" />
            <limiter name="CameraFps"  temp="370" value="-1:1"    />
        </scenario>

        <scenario name="MultiWindow" tempType="SKIN" priority="2" >
            <limiter name="CPUFreqMax" step="0" temp="340:360:410:430:450:470" value="-1:1536000:1536000:1344000:1344000:1056000" />
        </scenario>

         <scenario name="HighBrightness"  tempType="SKIN*BAT" priority="1" region="XSG" >
            <limiter name="CpLowMode" temp="440.370:450.380:470.400" value="-1:1:1" delay="0:1800:0" />
            <limiter name="SADisable" temp="440.370:450.380:470.400" value="-1:1:1" delay="0:1800:0" />
        </scenario>

         <scenario name="HighBrightness"  tempType="SKIN*BAT" priority="1" region="KSA" >
            <limiter name="CpLowMode" temp="440.370:450.380:470.400" value="-1:1:1" delay="0:1800:0" />
            <limiter name="SADisable" temp="440.370:450.380:470.400" value="-1:1:1" delay="0:1800:0" />
        </scenario>

        <scenario name="SpkHeatControl" tempType="SKIN" priority="2">
            <limiter name="CPUFreqMax" step="0" temp="340"     value="-1:2112000:1440000:1056000" />
            <limiter name="SpeakerControl"      temp="340"     value="-1:1"                      />
        </scenario>

        <scenario name="SmartSwitchTransfer" tempType="SKIN" priority="2" >
            <limiter name="CPUFreqMax"       tempType="SKIN" temp="360" p="50" i="1" d="30" unit="1000" min="1056000"/>
            <limiter name="CPUFreqLittleMax" temp="330:340:360:370"         value="-1:1344000:1152000:1056000"       />
            <limiter name="OverLimit"        temp="400"                     value="1536000:-1"                      />
            <limiter name="Charging"         temp="300:320:350:370"         value="-1:70:70:0"                      />
            <limiter name="WifiP2pTput"      temp="310:330:340:360:400:450" value="-1:400:300:200:100:50"           />
            <limiter name="JobRestriction"   temp="340"                     value="1" />
        </scenario>

        <scenario name="SmartSwitchAppInstall" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax"         tempType="SKIN" temp="360" p="50" i="1" d="30" unit="1000" min="1056000"/>
            <limiter name="CPUFreqLittleMax"   temp="330:340:360:370"         value="-1:1344000:1152000:1056000"       />
            <limiter name="OverLimit"          temp="360"                     value="2400000:2112000:1536000:-1"       />
            <limiter name="Charging"           temp="300:320:350:370"         value="-1:70:70:0"                      />
            <limiter name="JobRestriction"     temp="340"                     value="1" />
        </scenario>

        <scenario name="SmartView!ScreenMirroring_enable" tempType="SKIN" priority="2" >
             <limiter name="CPUFreqMax" temp="360"                         value="-1:2208000:1920000:1728000" />
             <limiter name="CPUFreqLittleMax"                              value="2016000"            />
             <limiter name="Brightness" temp="350:370:390:430:450"         value="225:138:113:113:87" />
             <limiter name="Charging"   temp="300:320:360:380"             value="-1:70:70:20"        />
         </scenario>

        <scenario name="Heavyuser" tempType="SKIN" priority="2" >
             <limiter name="CPUFreqMax" tempType="SKIN" temp="430" p="50" i="1" d="30" unit="1000" min="1632000"/>
             <limiter name="GPUFreqMax" tempType="SKIN" temp="430" p="50" i="1" d="30" unit="400" min="611000" />
         </scenario>

        <scenario name="SecCamera:com.sec.android.app.camera" tempType="SKIN" priority="1" >
            <limiter name="PowerBackOff" temp="400"  value="-1:1" region="VZW" />
        </scenario>

        <scenario name="ARemoji:com.samsung.android.aremoji" tempType="SKIN" priority="1" >
            <limiter name="GPUFreqMax" value="312000" />
        </scenario>

        <scenario name="ARDoodle:com.samsung.android.ardrawing" tempType="SKIN" priority="1" >
            <limiter name="GPUFreqMax" value="312000" />
        </scenario>

        <scenario name="BrowserApp" tempType="SKIN" priority="1">
            <limiter name="CPUFreqMax" step="0" temp="320:340:420:440:470" value="-1:1344000:1344000:1152000:1056000" />
            <limiter name="OverLimit"           temp="380"                      value="2400000:-1" />
            <limiter name="GPUFreqMax" step="0" temp="340:360:400:420"         value="-1:611000:611000:403000" />
        </scenario>

        <scenario name="HeavyLoadApp" tempType="SKIN" priority="1">
            <limiter name="CPUFreqMax" step="0" temp="320:340:420:440:470" value="-1:1344000:1344000:1152000:1056000" />
            <limiter name="OverLimit"           temp="360"                      value="2400000:-1" />
            <limiter name="CPUFreqLittleMax"    temp="420"         value="-1:1056000" />
            <limiter name="GPUFreqMax" step="0" temp="340:360:400:420"         value="-1:611000:611000:403000" />
        </scenario>

        <scenario name="ChinaVideo:com.duowan.kiwi,com.huya.kiwi" tempType="SKIN" priority="2">
            <limiter name="CPUFreqMax" step="0" temp="310:330:350:370:450:470"  value="-1:1536000:1344000:1248000:1248000:1056000" />
            <limiter name="OverLimit"           temp="450"                      value="1632000:-1" />
            <limiter name="CPUFreqLittleMax"    temp="310:330:350:370:450:470"  value="-1:1728000:1632000:1536000:1536000:1056000" />
        </scenario>

        <scenario_group name="GameThermalCpuControl" tempType="SKIN" >
            <scenario id="-6"  limiter="CPUFreqMax"                             value="960000" />
            <scenario id="-5"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1632000:960000" />
            <scenario id="-4"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1632000:1056000" />
            <scenario id="-3"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1632000:1152000" />
            <scenario id="-2"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1632000:1344000" />
            <scenario id="-1"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1632000:1536000" />
            <scenario id="0"   limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1824000:1632000" />
            <scenario id="1"   limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:2112000:1824000" />
            <scenario id="2"   limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:2288000:2112000" />
            <scenario id="3"   limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:2400000:2288000" />
            <scenario id="4"   limiter="CPUFreqMax"                             value="-1"                 />
        </scenario_group>

        <scenario_group name="GameThermalGpuControl" tempType="SKIN" >
            <scenario id="-5" limiter="GPUFreqMax"                             value="208000" />
            <scenario id="-4" limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:312000:208000" />
            <scenario id="-3" limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:403000:312000" />
            <scenario id="-2" limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:507000:403000" />
            <scenario id="-1" limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:611000:507000" />
            <scenario id="0"  limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:702000:611000" />
            <scenario id="1"  limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:897000:702000" />
            <scenario id="2"  limiter="GPUFreqMax"                             value="-1"               />
        </scenario_group>

    </scenarios>

</siop_document>
